<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $note->title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #333333;
            line-height: 1.6;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            border-bottom: 2px solid #4e73df;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        .title {
            font-size: 26px;
            font-weight: bold;
            color: #2c3e50;
            margin: 0 0 10px 0;
        }
        .meta-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        .meta-table td {
            padding: 4px 0;
            vertical-align: top;
        }
        .meta-label {
            font-weight: bold;
            color: #7f8c8d;
            width: 120px;
        }
        .meta-value {
            color: #2c3e50;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            font-size: 11px;
            font-weight: bold;
            color: #ffffff;
            border-radius: 4px;
            text-transform: uppercase;
        }
        .badge-personal { background-color: #1cc88a; }
        .badge-project { background-color: #4e73df; }
        .badge-task { background-color: #f6c23e; color: #333333; }
        .badge-org { background-color: #36b9cc; }
        .joypixels {
            height: 1.1em;
            width: 1.1em;
            vertical-align: middle;
            margin: 0 2px;
        }
        
        .content {
            margin-top: 20px;
            font-size: 15px;
            color: #2c3e50;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1 class="title">{{ $note->title }}</h1>
        <div style="font-size: 13px; color: #7f8c8d; margin-top: -5px; margin-bottom: 15px;">
            Written by {{ $note->user ? $note->user->name : 'System User' }}
        </div>
        <table class="meta-table">
            <tr>
                <td class="meta-label">Note Scope:</td>
                <td class="meta-value">
                    @if($note->note_type == 4)
                        <span class="badge badge-personal">Personal</span>
                    @elseif($note->note_type == 1)
                        <span class="badge badge-project">Project Note</span>
                    @elseif($note->note_type == 2)
                        <span class="badge badge-task">Task Note</span>
                    @elseif($note->note_type == 3)
                        <span class="badge badge-org">Organization</span>
                    @endif
                </td>
            </tr>
            @if($note->noteable)
                <tr>
                    <td class="meta-label">Reference:</td>
                    <td class="meta-value">
                        @if($note->note_type == 1)
                            {{ $note->noteable->name }} (Project)
                        @elseif($note->note_type == 2)
                            {{ $note->noteable->title }} (Task)
                        @elseif($note->note_type == 3)
                            {{ $note->noteable->name }} (Organization)
                        @endif
                    </td>
                </tr>
            @endif
            @if($note->user)
                <tr>
                    <td class="meta-label">Author:</td>
                    <td class="meta-value">{{ $note->user->name }}</td>
                </tr>
            @endif
            <tr>
                <td class="meta-label">Created At:</td>
                <td class="meta-value">{{ $note->created_at->format('F d, Y h:i A') }}</td>
            </tr>
            @if($note->updated_at != $note->created_at)
                <tr>
                    <td class="meta-label">Updated At:</td>
                    <td class="meta-value">{{ $note->updated_at->format('F d, Y h:i A') }}</td>
                </tr>
            @endif
        </table>
    </div>

    <div class="content">
        {!! $noteDescription !!}
    </div>

    <div class="footer">
        Generated by WorkHub Management System &bull; {{ now()->format('Y-m-d H:i') }}
    </div>

</body>
</html>
